changelog:
  categories:
    - title: "🚀 Features & Enhancements"
      labels:
        - "enhancement"
        - "feature"
    - title: "🛡️ Security & Reliability"
      labels:
        - "security"
        - "reliability"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "📚 Documentation"
      labels:
        - "documentation"
