"""Realistic mock email dataset for offline development, demonstrations, and testing."""

from typing import List
from inboxgpt.gmail.models import EmailCategory, EmailMessage

MOCK_EMAILS: List[EmailMessage] = [
    EmailMessage(
        id="msg_001",
        thread_id="th_001",
        sender="sarah.connor@acmecorp.com",
        sender_name="Sarah Connor",
        recipient="user@example.com",
        subject="URGENT: Q3 Security Audit & Production Release signoff",
        snippet="Hi team, we need everyone's signoff on the security audit report before 5 PM today...",
        body="Hi team,\n\nWe need everyone's signoff on the security audit report before 5 PM today. The prod cluster migration depends on this. Please review the attached findings and confirm.\n\nBest,\nSarah Connor\nVP of Engineering",
        date="2026-10-07 08:30:00",
        labels=["INBOX", "UNREAD", "IMPORTANT"],
        is_unread=True,
        category=EmailCategory.IMPORTANT,
        importance_reason="Direct manager request requiring urgent response today before 5 PM",
    ),
    EmailMessage(
        id="msg_002",
        thread_id="th_002",
        sender="dan@tldrnewsletter.com",
        sender_name="TLDR Tech",
        recipient="user@example.com",
        subject="TLDR Tech: Anthropic launches Claude 4, Google updates Gemini reasoning models",
        snippet="Anthropic announces new benchmark scores / Meta opens weights for multimodal model...",
        body="TLDR Tech Newsletter - October 7, 2026\n\n1. AI & LLMs: Anthropic released benchmark scores showcasing advanced coding performance...\n2. Cloud Computing: Google Cloud introduces new latency optimizations...",
        date="2026-10-07 07:15:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.NEWSLETTER,
        importance_reason="Daily tech digest",
    ),
    EmailMessage(
        id="msg_003",
        thread_id="th_003",
        sender="notifications@github.com",
        sender_name="GitHub",
        recipient="user@example.com",
        subject="[langchain-ai/langgraph] Pull Request #1420 merged: Add interrupt resume tests",
        snippet="Merged by @hwchase17: Add unit test coverage for LangGraph interrupt commands...",
        body="Pull request #1420 has been merged into main.\n\nAuthor: contributor\nReviewer: @hwchase17\nChanges: +145 / -22\n\nYou are receiving this notification because you are subscribed to this repository.",
        date="2026-10-07 06:45:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.SOCIAL,
        importance_reason="Automated git repository notification",
    ),
    EmailMessage(
        id="msg_004",
        thread_id="th_004",
        sender="offers@uber.com",
        sender_name="Uber Eats",
        recipient="user@example.com",
        subject="🍕 50% OFF your next 3 orders this week only!",
        snippet="Craving sushi or pizza? Save up to $25 with promo code TASTY50 right now...",
        body="Special discount just for you!\n\nUse promo code TASTY50 at checkout to receive 50% off your next 3 lunch orders. Valid through Friday midnight.",
        date="2026-10-06 18:20:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.PROMOTIONAL,
        importance_reason="Commercial marketing email offering limited-time food discount",
    ),
    EmailMessage(
        id="msg_005",
        thread_id="th_005",
        sender="deals@amazon.com",
        sender_name="Amazon Deals",
        recipient="user@example.com",
        subject="Lightning Deals on Mechanical Keyboards & Ergonomic Chairs",
        snippet="Check out today's top picks in electronics and home office furniture...",
        body="Amazon Daily Deals\n\nExclusive discounts on Keychron wireless keyboards, Herman Miller chairs, and 4K gaming monitors. Click to view all promotions.",
        date="2026-10-06 14:10:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.PROMOTIONAL,
        importance_reason="Marketing promotion for electronics",
    ),
    EmailMessage(
        id="msg_006",
        thread_id="th_006",
        sender="growth-lead@b2bleads-solution-ai.xyz",
        sender_name="Alex from GrowthScale",
        recipient="user@example.com",
        subject="Quick question about scaling your outbound sales pipeline?",
        snippet="Hey, I noticed your company was hiring. We guarantee 50 qualified B2B demos a month...",
        body="Hi there,\n\nI noticed you are leading technical initiatives. Have you thought about automating outbound SDR workflows? We can guarantee 50 qualified enterprise meetings in 30 days.\n\nGot 10 mins this Thursday for a quick demo?\n\nAlex",
        date="2026-10-06 11:05:00",
        labels=["INBOX", "UNREAD"],
        is_unread=True,
        category=EmailCategory.UNWANTED,
        importance_reason="Unsolicited cold sales outreach spam",
    ),
    EmailMessage(
        id="msg_007",
        thread_id="th_007",
        sender="investor-updates@stripe.com",
        sender_name="Stripe Billing",
        recipient="user@example.com",
        subject="Your Stripe Monthly Invoice #INV-2026-9938 is now available",
        snippet="Your receipt for $42.00 is attached. Payment processed successfully via Visa ending in 4242...",
        body="Hello,\n\nYour monthly billing statement for September 2026 is ready.\n\nAmount charged: $42.00 USD\nPayment Method: Visa ending in 4242\nStatus: Paid\n\nThank you for using Stripe.",
        date="2026-10-05 09:00:00",
        labels=["INBOX", "IMPORTANT"],
        is_unread=False,
        category=EmailCategory.IMPORTANT,
        importance_reason="Monthly financial billing invoice and receipt",
    ),
    EmailMessage(
        id="msg_008",
        thread_id="th_008",
        sender="noreply@linkedin.com",
        sender_name="LinkedIn",
        recipient="user@example.com",
        subject="You appeared in 47 searches this week, plus 3 new connection requests",
        snippet="See who is looking at your profile on LinkedIn: recruiters from Google, OpenAI...",
        body="Weekly LinkedIn update:\n- 47 profile views\n- 3 connection requests awaiting your reply\n- 5 new jobs matching 'Senior AI Systems Engineer'",
        date="2026-10-05 08:30:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.SOCIAL,
        importance_reason="Social network activity summary",
    ),
    EmailMessage(
        id="msg_009",
        thread_id="th_009",
        sender="weekly@pragmaticengineer.com",
        sender_name="Gergely Orosz",
        recipient="user@example.com",
        subject="The Pragmatic Engineer: How big tech companies evaluate AI coding assistants",
        snippet="Inside the developer productivity benchmarks at Meta, Uber, and Datadog...",
        body="Welcome to this week's edition of The Pragmatic Engineer.\n\nToday, we look into internal engineering metric changes as AI-assisted software generation becomes standard practice...",
        date="2026-10-04 16:00:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.NEWSLETTER,
        importance_reason="Engineering leadership newsletter",
    ),
    EmailMessage(
        id="msg_010",
        thread_id="th_010",
        sender="promotions@booking.com",
        sender_name="Booking.com",
        recipient="user@example.com",
        subject="Flash Deal: 30% off weekend getaways in Kyoto and Tokyo",
        snippet="Book by midnight to lock in exclusive member rates at luxury ryokans...",
        body="Autumn in Japan!\n\nExclusive getaway discounts available for loyalty members. Book before October 10th to claim your voucher.",
        date="2026-10-04 10:15:00",
        labels=["INBOX"],
        is_unread=False,
        category=EmailCategory.PROMOTIONAL,
        importance_reason="Travel promotional offer",
    ),
    EmailMessage(
        id="msg_011",
        thread_id="th_011",
        sender="rich-crypto-invest@binance-crypto-airdrop.buzz",
        sender_name="Crypto Rewards Team",
        recipient="user@example.com",
        subject="CLAIM YOUR 5,000 USDT AIRDROP IMMEDIATELY - EXPIRES IN 2 HOURS",
        snippet="You have been randomly selected to receive a promotional grant of 5,000 Tether tokens...",
        body="Congratulations!\n\nYour wallet address has won 5,000 USDT. Click the secure portal link below to connect your Web3 wallet and authorize claim immediately.\n\nWARNING: Link valid for 2 hours.",
        date="2026-10-03 23:45:00",
        labels=["INBOX", "UNREAD"],
        is_unread=True,
        category=EmailCategory.UNWANTED,
        importance_reason="Phishing / crypto scam unsolicited email",
    ),
    EmailMessage(
        id="msg_012",
        thread_id="th_012",
        sender="cto@mycompany.internal",
        sender_name="Marcus Vance",
        recipient="user@example.com",
        subject="Confidential: 2027 Roadmap Planning & Architecture Decision Record",
        snippet="Please keep this internal. I'd like your thoughts on migrating our agent runtimes...",
        body="Hi,\n\nWe need to lock down our architecture decision for the 2027 AI agent roadmap next Monday. Could you compile a 1-page summary of our latency and safety evaluations?\n\nThanks,\nMarcus",
        date="2026-10-03 14:12:00",
        labels=["INBOX", "UNREAD", "IMPORTANT"],
        is_unread=True,
        category=EmailCategory.IMPORTANT,
        importance_reason="Executive architecture decision request",
    ),
]
