"""Agent state schema for LangGraph inbox triage and cleanup pipeline."""

from typing import Annotated, Any, Dict, List, Optional
from typing_extensions import TypedDict
import operator

from inboxgpt.gmail.models import (
    ActionResult,
    EmailMessage,
    InboxStats,
    ProposedAction,
)


class AgentState(TypedDict, total=False):
    """LangGraph state schema representing inbox state, classification, and proposed actions."""

    # Raw emails fetched from Gmail
    emails: List[EmailMessage]

    # Category mappings: category_value -> list of message IDs
    categorized_emails: Dict[str, List[str]]

    # Statistical breakdown of the inbox
    stats: InboxStats

    # Proposed actions generated by the AI agent awaiting review
    proposed_actions: List[ProposedAction]

    # User decisions: approved & rejected action IDs
    approved_action_ids: List[str]
    rejected_action_ids: List[str]

    # Results of executing approved actions
    action_results: List[ActionResult]

    # Comprehensive triage report
    summary_report: str

    # Pipeline lifecycle status
    status: str

    # Data injected when resuming an interrupt
    user_approval_decision: Optional[Dict[str, Any]]
